spring:
  datasource:
    url: jdbc:mariadb://${spring_datasource_url}:3306/tutorial
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect